import type { Product } from "@/types";

export const demoProducts: Product[] = [
  {
    _id: "1",
    name: "Royal Chronograph Gold",
    slug: "royal-chronograph-gold",
    sku: "RW-RCG-001",
    brand: "Rehmat",
    category: "chronograph",
    gender: "men",
    strapType: "metal",
    color: "Gold",
    description:
      "An exquisite chronograph featuring a sunburst gold dial, sapphire crystal, and Swiss automatic movement. A statement piece for the discerning gentleman.",
    specifications: {
      movement: "Swiss Automatic",
      caseSize: "42mm",
      caseMaterial: "Stainless Steel Gold Plated",
      waterResistance: "100m",
      dialColor: "Gold Sunburst",
      crystal: "Sapphire",
      warranty: "2 Years International",
    },
    price: 89500,
    discountPrice: 74900,
    stock: 15,
    images: [
      "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&q=80",
      "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80",
    ],
    featured: true,
    bestSeller: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 124,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "2",
    name: "Elegance Diamond",
    slug: "elegance-diamond",
    sku: "RW-ED-002",
    brand: "Rehmat",
    category: "luxury",
    gender: "women",
    strapType: "leather",
    color: "Rose Gold",
    description:
      "A stunning ladies timepiece adorned with diamond indices and a mother-of-pearl dial. Elegance redefined for the modern woman.",
    specifications: {
      movement: "Quartz",
      caseSize: "32mm",
      caseMaterial: "Rose Gold Plated",
      waterResistance: "50m",
      dialColor: "Mother of Pearl",
      crystal: "Sapphire",
      warranty: "2 Years International",
    },
    price: 125000,
    stock: 8,
    images: [
      "https://images.unsplash.com/photo-1547996160-81dfa62995e0?w=800&q=80",
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&q=80",
    ],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.9,
    reviewCount: 89,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "3",
    name: "Deep Sea Diver Pro",
    slug: "deep-sea-diver-pro",
    sku: "RW-DSD-003",
    brand: "Rehmat",
    category: "diver",
    gender: "men",
    strapType: "rubber",
    color: "Black",
    description:
      "Professional dive watch rated to 300m with unidirectional rotating bezel and luminous markers. Built for adventure.",
    specifications: {
      movement: "Automatic",
      caseSize: "44mm",
      caseMaterial: "Titanium",
      waterResistance: "300m",
      dialColor: "Black",
      crystal: "Sapphire",
      warranty: "3 Years International",
    },
    price: 67500,
    discountPrice: 59900,
    stock: 22,
    images: [
      "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800&q=80",
      "https://images.unsplash.com/photo-1614164185128-e4ec99c436d6?w=800&q=80",
    ],
    featured: false,
    bestSeller: true,
    newArrival: false,
    rating: 4.7,
    reviewCount: 203,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "4",
    name: "Classic Dress Heritage",
    slug: "classic-dress-heritage",
    sku: "RW-CDH-004",
    brand: "Rehmat",
    category: "dress",
    gender: "men",
    strapType: "leather",
    color: "Brown",
    description:
      "Timeless dress watch with a clean white dial and genuine Italian leather strap. Perfect for formal occasions.",
    specifications: {
      movement: "Manual Wind",
      caseSize: "40mm",
      caseMaterial: "Stainless Steel",
      waterResistance: "30m",
      dialColor: "White",
      crystal: "Sapphire",
      warranty: "2 Years International",
    },
    price: 45000,
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1522312346375-d1a52e9bdea0?w=800&q=80",
      "https://images.unsplash.com/photo-1612817159947-19598edcd2cd?w=800&q=80",
    ],
    featured: true,
    bestSeller: true,
    newArrival: false,
    rating: 4.6,
    reviewCount: 156,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "5",
    name: "Sport Titanium Elite",
    slug: "sport-titanium-elite",
    sku: "RW-STE-005",
    brand: "Rehmat",
    category: "sport",
    gender: "unisex",
    strapType: "metal",
    color: "Silver",
    description:
      "Lightweight titanium sport watch with tachymeter bezel and chronograph functions. Performance meets luxury.",
    specifications: {
      movement: "Quartz Chronograph",
      caseSize: "43mm",
      caseMaterial: "Titanium",
      waterResistance: "200m",
      dialColor: "Blue",
      crystal: "Sapphire",
      warranty: "2 Years International",
    },
    price: 55000,
    discountPrice: 47900,
    stock: 18,
    images: [
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=800&q=80",
      "https://images.unsplash.com/photo-1508685098649-9aacd3260913?w=800&q=80",
    ],
    featured: false,
    bestSeller: false,
    newArrival: true,
    rating: 4.5,
    reviewCount: 67,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "6",
    name: "Midnight Black Edition",
    slug: "midnight-black-edition",
    sku: "RW-MBE-006",
    brand: "Rehmat",
    category: "luxury",
    gender: "men",
    strapType: "ceramic",
    color: "Black",
    description:
      "All-black ceramic masterpiece with skeleton dial revealing the intricate automatic movement within.",
    specifications: {
      movement: "Automatic Skeleton",
      caseSize: "41mm",
      caseMaterial: "Black Ceramic",
      waterResistance: "50m",
      dialColor: "Skeleton",
      crystal: "Sapphire",
      warranty: "3 Years International",
    },
    price: 185000,
    stock: 5,
    images: [
      "https://images.unsplash.com/photo-1611395917755-60603fecd90c?w=800&q=80",
      "https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=800&q=80",
    ],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 5.0,
    reviewCount: 42,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "7",
    name: "Pearl Elegance",
    slug: "pearl-elegance",
    sku: "RW-PE-007",
    brand: "Rehmat",
    category: "dress",
    gender: "women",
    strapType: "metal",
    color: "Silver",
    description:
      "Delicate silver timepiece with pearl dial and diamond hour markers. A jewel for your wrist.",
    specifications: {
      movement: "Quartz",
      caseSize: "28mm",
      caseMaterial: "Sterling Silver",
      waterResistance: "30m",
      dialColor: "Pearl White",
      crystal: "Sapphire",
      warranty: "2 Years International",
    },
    price: 72000,
    stock: 12,
    images: [
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=800&q=80",
      "https://images.unsplash.com/photo-1622438641438-40965ba0e6ed?w=800&q=80",
    ],
    featured: false,
    bestSeller: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 98,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "8",
    name: "Aviator GMT Master",
    slug: "aviator-gmt-master",
    sku: "RW-AGM-008",
    brand: "Rehmat",
    category: "sport",
    gender: "men",
    strapType: "leather",
    color: "Brown",
    description:
      "Dual-timezone GMT watch inspired by aviation heritage. Track two time zones with precision.",
    specifications: {
      movement: "Automatic GMT",
      caseSize: "42mm",
      caseMaterial: "Stainless Steel",
      waterResistance: "100m",
      dialColor: "Black",
      crystal: "Sapphire",
      warranty: "2 Years International",
    },
    price: 82000,
    discountPrice: 69900,
    stock: 10,
    images: [
      "https://images.unsplash.com/photo-1548171915-e79a380a9a95?w=800&q=80",
      "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&q=80",
    ],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.7,
    reviewCount: 73,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoBanners = [
  {
    _id: "b1",
    title: "Timeless Luxury On Your Wrist",
    subtitle: "Discover our exclusive collection of premium timepieces",
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=1920&q=80",
    link: "/shop",
    type: "hero" as const,
    active: true,
    order: 0,
  },
  {
    _id: "b2",
    title: "New Arrivals 2026",
    subtitle: "Be the first to own our latest masterpieces",
    image: "https://images.unsplash.com/photo-1611395917755-60603fecd90c?w=1920&q=80",
    link: "/shop?filter=newArrival",
    type: "hero" as const,
    active: true,
    order: 1,
  },
  {
    _id: "b3",
    title: "Summer Collection",
    subtitle: "Up to 30% off selected models",
    image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=1920&q=80",
    link: "/shop?filter=sale",
    type: "hero" as const,
    active: true,
    order: 2,
  },
  {
  _id: "b4",
  title: "Classic Elegance",
  subtitle: "Precision, craftsmanship, and style that lasts forever",
  image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=1920&q=80",
  link: "/shop?filter=classic",
  type: "hero" as const,
  active: true,
  order: 3,
},
{
  _id: "b5",
  title: "Built for Every Moment",
  subtitle: "Premium watches designed for confidence, style, and performance",
  image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=1920&q=80",
  link: "/shop?filter=mens",
  type: "hero" as const,
  active: true,
  order: 4,
},
];
  export const demoReviews = [
  {
    _id: "r1",
    productId: "1",
    userId: "u1",
    userName: "Ahmed Khan",
    rating: 5,
    comment: "Absolutely stunning watch! The craftsmanship is exceptional and it looks even better in person.",
    approved: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "r2",
    productId: "3",
    userId: "u2",
    userName: "Sarah Malik",
    rating: 5,
    comment: "Perfect dive watch. Took it snorkeling and it performed flawlessly. Highly recommend!",
    approved: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "r3",
    productId: "2",
    userId: "u3",
    userName: "Fatima Ali",
    rating: 5,
    comment: "The most beautiful watch I own. The diamond details are exquisite. Worth every penny.",
    approved: true,
    createdAt: new Date().toISOString(),
  },
];
